title: Adamatti - blog pessoal
email: adamatti@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Espaço para compartilhar conhecimento, minhas opiniões, notícias que eu considero relevante.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://adamatti.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: adamatti
github_username:  adamatti
disqus:
  shortname: http-adamatti-github-io-blog
google_analytics: UA-1039281-11
minima:
  date_format: "%Y-%m-%d"

asciidoctor:
  attributes:
    - source-highlighter=pygments
tag_page_layout: tag_page
tag_page_dir: tag

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-asciidoc
  - pygments.rb
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - Rakefile